doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                dbname: '%env(DATABASE_NAME)%'
                host: '%env(DATABASE_HOST)%'
                port: '%env(DATABASE_PORT)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                charset:  UTF8
