version: '3'

services:
  mysql:
    container_name: product-catalog-db
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_DATABASE=mysql_database
      - MYSQL_USER=mysql_user
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysql_password
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - default
  php-fpm:
    container_name: product-catalog-php-fpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - mysql
    working_dir: /product-catalog-api
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./:/product-catalog-api:cached
    networks:
      - default
  nginx:
    container_name: product-catalog-nginx
    image: nginx
    volumes:
      - ./:/product-catalog-api
      - ./:/product-catalog-api/vendor:cached
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/ssl/:/etc/nginx/ssl/
    depends_on:
      - php-fpm
      - mysql
    ports:
      - 80:8080
      - 443:443
    networks:
      - default
  redis:
    container_name: product-catalog-redis
    image: redis:buster
    restart: always
    networks:
      - default
    ports:
      - 6379:6379
networks:
  default:
