parameters:
    product.event_stream.name: 'product_event_stream'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $sharedEventBus: '@messenger.bus.event.product'
            $productCommandBus: '@messenger.bus.command.product'
            $productQueryBus: '@messenger.bus.query.product'
            $productEventStreamName: '%product.event_stream.name%'
            $productEventStore: '@api.shared_kernel.action_event_emitter_event_store'
            $productSnapshotStore: '@api.snapshot_store.offer'
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'
    App\API\:
        resource: '../src/API'
        tags: ['controller.service_arguments']



