parameters:
    product.event_stream.name: 'product_event_stream'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $sharedEventBus: '@messenger.bus.event.product'
            $productCommandBus: '@messenger.bus.command.product'
            $productQueryBus: '@messenger.bus.query.product'
            $productEventStreamName: '%product.event_stream.name%'
            $productEventStore: '@app.shared_kernel.action_event_emitter_event_store'
            $productSnapshotStore: '@app.snapshot_store.offer'
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Predis\ClientInterface:
        alias: snc_redis.default

    App\SharedKernel\EventListener\UnhandledExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Infrastructure\ProductRepositoryInterface:
        class: App\Infrastructure\ProductRepository\EventStore

    App\Infrastructure\ProductViewRepositoryInterface:
        class: App\Infrastructure\ProductViewRepository\PDO
